//alert("JavaScript funcionando correctamente");
let variableSinValor;
let booleano1 = true;
let booleano2 = false;
const PI = 3.14;
const TAU = 2 * PI;
const miNombre = "Pablo";
let miNumeroFav = 33;
let bool;
console.log(miNombre.length);
console.log(typeof miNumeroFav);
console.log("Mi nombre es " + miNombre + " y mi numero favorito es " + miNumeroFav);
const texto = "Seré un crack en JavaScript al terminar el bootcamp";
console.log(texto.toUpperCase());
const hola = "Hola soy un crack";
console.log(hola.substring(0, 4));
miNumeroFav = miNumeroFav.toString();
console.log(typeof miNumeroFav);
let variable = "Variable";
let templateLiteral = `Esta es la varible: ${variable}`;
console.log(templateLiteral);
console.log(PI.toFixed(2));